services:
    Gupalo\BrowserNotifier:
        autowire: true

    Gupalo\BrowserNotifier\Twig\:
        resource: '%kernel.project_dir%/vendor/gupalo/browser-notifier/src/Twig'
        tags: ['twig.extension']
